#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


COMMAND="${1:-help}"
shift || true

# Loading all the files to memory to run command functions
for file in "$SCRIPT_DIR"/commands/*.sh; do
    source "$file"
done


# Command passed from snapshot
case "$COMMAND" in 
    backup)
        cmd_backup "$@"
        ;;
    restore)
        cmd_restore "$@"
        ;;
    init)
        cmd_init "$@"
        ;;
    install)
        source "$SCRIPT_DIR/install.sh"
        cmd_install "$@"
        ;;
    reinstall)
        source "$SCRIPT_DIR/install.sh"
        cmd_install "reinstall"
        ;;
    alias)
        cmd_alias "$@"
        ;;
    clear)
        cmd_clear "$@"
        ;;
    help|*)
        cmd_help "$@"
esac